#! /bin/bash
###############################################################################
#                                                                             #
#                                  Alice                                      #
#                                                                             #
#                            Tests Build Script                               #
#                                                                             #
#                       Copyright (C) 2012-, AdaHeads K/S                     #
#                                                                             #
#  This is free software;  you can redistribute it  and/or modify it          #
#  under terms of the  GNU General Public License as published  by the        #
#  Free Software  Foundation;  either version 3,  or (at your option) any     #
#  later version.  This software is distributed in the hope  that it will     #
#  be useful, but WITHOUT ANY WARRANTY;  without even the implied warranty    #
#  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        #
#  General Public License for  more details.                                  #
#  You should have  received  a copy of the GNU General  Public  License      #
#  distributed  with  this  software;   see  file COPYING3.  If not, go       #
#  to http://www.gnu.org/licenses for a complete copy of the license.         #
#                                                                             #
###############################################################################

cd "$(dirname "$0")" || exit -1

failed_list=$(mktemp)
succeeded_list=$(mktemp)

for file in $(find ./ -mindepth 2 -type f -name \*.gpr | sort); do
   test=$(echo ${file} | cut -d/ -f2)

   if gnatmake -P ${file} 1>${file}.output \
                          2>${file}.errors; then
      echo ${test} >> ${succeeded_list}
   else
      echo ${test} >>    ${failed_list}
   fi
done

total=$(cat ${succeeded_list} ${failed_list} | wc -l)
failed=$(cat ${failed_list} | wc -l)

if [ -s ${failed_list} ]; then
   echo "${failed} out of ${total} builds failed:"
   uniq < ${failed_list}
else
   echo "All ${total} builds succeeded."
fi

rm -f ${failed_list} ${succeeded_list}

exit ${failed}
