#! /bin/bash

cd "$(dirname "$0")" || exit -1

failed_list=$(mktemp)
succeeded_list=$(mktemp)

for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
   test=$(echo ${file} | cut -d/ -f2)

   if [ ! -f ${file}.arguments ]; then
      touch ${file}.arguments
   fi
   
   if ./${file} $(cat ${file}.arguments) 1>${file}.output \
                                         2>${file}.errors; then
      echo ${test} >> ${succeeded_list}
   else
      echo ${test} >>    ${failed_list}
   fi
done

total=$(cat ${succeeded_list} ${failed_list} | wc -l)
failed=$(cat ${failed_list} | wc -l)

if [ -s ${failed_list} ]; then
   echo "${failed} out of ${total} tests failed:"
   uniq < ${failed_list}
else
   echo "All ${total} tests succeeded."
fi

rm -f ${failed_list} ${succeeded_list}

exit ${failed}
