#! /bin/bash
###############################################################################
#                                                                             #
#                                  Alice                                      #
#                                                                             #
#                             Tests Run Script                                #
#                                                                             #
#                       Copyright (C) 2012-, AdaHeads K/S                     #
#                                                                             #
#  This is free software;  you can redistribute it  and/or modify it          #
#  under terms of the  GNU General Public License as published  by the        #
#  Free Software  Foundation;  either version 3,  or (at your option) any     #
#  later version.  This software is distributed in the hope  that it will     #
#  be useful, but WITHOUT ANY WARRANTY;  without even the implied warranty    #
#  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        #
#  General Public License for  more details.                                  #
#  You should have  received  a copy of the GNU General  Public  License      #
#  distributed  with  this  software;   see  file COPYING3.  If not, go       #
#  to http://www.gnu.org/licenses for a complete copy of the license.         #
#                                                                             #
###############################################################################

default_allowed_time_in_seconds=10

cd "$(dirname "$0")" || exit -1

failed_list=$(mktemp)
succeeded_list=$(mktemp)

echo -n "Running tests...   "

for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
   if [ ! -f ${file}.arguments ]; then
      touch ${file}.arguments
   fi

   if [ -f ${file}.allowed_time_in_seconds ]; then
      allowed_time_in_seconds=$(cat ${file}.allowed_time_in_seconds)
   else
      allowed_time_in_seconds=${default_allowed_time_in_seconds}
   fi

   ./${file} $(cat ${file}.arguments) 1>${file}.output \
                                      2>${file}.errors \
                                      &
   pid=$!

   (
     sleep ${allowed_time_in_seconds}
     kill ${pid} 2>/dev/null
     sleep 1
     kill -9 ${pid} 2>/dev/null
   ) &

   wait ${pid}
   result=$?

   if [ ${result} -eq 0 ]; then
      echo "${file}"             >> ${succeeded_list}
   else
      echo "${file} (${result})" >>    ${failed_list}
   fi
done 2>/dev/null

total=$(cat ${succeeded_list} ${failed_list} | wc -l)
failed=$(cat ${failed_list} | wc -l)

if [ -s ${failed_list} ]; then
   echo "${failed} out of ${total} tests failed:"
   uniq < ${failed_list} | sed 's|^|  |'
else
   echo "All ${total} tests succeeded."
fi

rm -f ${failed_list} ${succeeded_list}

exit ${failed}
