#! /bin/bash
###############################################################################
#                                                                             #
#                                  Alice                                      #
#                                                                             #
#                             Tests Run Script                                #
#                                                                             #
#                       Copyright (C) 2012-, AdaHeads K/S                     #
#                                                                             #
#  This is free software;  you can redistribute it  and/or modify it          #
#  under terms of the  GNU General Public License as published  by the        #
#  Free Software  Foundation;  either version 3,  or (at your option) any     #
#  later version.  This software is distributed in the hope  that it will     #
#  be useful, but WITHOUT ANY WARRANTY;  without even the implied warranty    #
#  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        #
#  General Public License for  more details.                                  #
#  You should have  received  a copy of the GNU General  Public  License      #
#  distributed  with  this  software;   see  file COPYING3.  If not, go       #
#  to http://www.gnu.org/licenses for a complete copy of the license.         #
#                                                                             #
###############################################################################

cd "$(dirname "$0")" || exit -1

failed_list=$(mktemp)
succeeded_list=$(mktemp)

echo "Running tests."

for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
   NAME=`basename ${file}`
   test=$(echo ${file} | cut -d/ -f2)

   if [ ! -f ${file}.arguments ]; then
      touch ${file}.arguments
   fi

   # Start the test and background it.
   ./${file} $(cat ${file}.arguments) 1>${file}.output \
                                      2>${file}.errors \
                                      &
   PID=$!

   COUNTER=0
   while [ -d /proc/${PID} ]; do
      let "COUNTER++"

      # Kill tests that run for more than 10 seconds.
      if [ "$COUNTER" -gt 20 ]; then
         echo "${NAME} seems stuck. Killing it."
         kill $PID 2>/dev/null
         wait $PID 2>/dev/null

         sleep 1 # Waiting 1 second for test to die nicely.

         if [ -d /proc/${PID} ]; then
            echo "${NAME} wont die nicely. Shooting it in the head with -9."
            kill -9 $PID 2>/dev/null
            wait $PID 2>/dev/null
         fi
      fi

      sleep 0.5
   done

   # Get information about the background test process.
   wait ${PID}

   if [ $? -eq 0 ]; then
      echo ${test} >> ${succeeded_list}
      echo "${NAME} completed."
   else
      echo ${test} >> ${failed_list}
      echo "${NAME} failed."

      # Reset success
      success="true"
   fi
done

total=$(cat ${succeeded_list} ${failed_list} | wc -l)
failed=$(cat ${failed_list} | wc -l)

if [ -s ${failed_list} ]; then
   echo "${failed} out of ${total} tests failed:"
   uniq < ${failed_list}
else
   echo "All ${total} tests succeeded."
fi

rm -f ${failed_list} ${succeeded_list}

exit ${failed}
