#! /bin/bash
#-----------------------------------------------------------------------------

source="$1"
target="$(dirname "$1")/sqlite/$(basename "$1")"

#-----------------------------------------------------------------------------
#--  Simple substitutions:

perl -lpe 's/TRUE/1/g;
           s/FALSE/0/g;
           s/(XML|JSON)/TEXT/g;
           s/, -- +AUTOINCREMENT *$/ AUTOINCREMENT,/;' \
     "${source}" \
  > "${target}"

#-----------------------------------------------------------------------------
#--  Remove ALTER TABLE on organization_contacts:

buffer="$(mktemp)"

grep -B4 -A4 'ALTER TABLE organization_contacts' "${target}" \
  | diff - "${target}" \
  | grep '^> ' \
  | cut -c3- \
  | perl -lpe 's/^( *distribution_list_id) .*$/$1 INTEGER NOT NULL REFERENCES distribution_lists (id) ON UPDATE CASCADE ON DELETE CASCADE,/;' \
  > "${buffer}"

mv "${buffer}" "${target}"

#-----------------------------------------------------------------------------
#--  Primary key indices:

if grep -q 'CREATE TABLE' "${source}"; then
   cat >> "${target}" << HEAD
--  Primary key indexes:

HEAD

   normalised="$(mktemp)"

   perl -lpe 's/--.*$//;' "$1" \
     | tr '\n' ' ' \
     | perl -lpe 's/; +/;/g; s/;/;\n/g; s/^ +//; s/  +/ /g;' \
     > "${normalised}"

   for table in $(grep 'CREATE TABLE' "${normalised}" | cut -d' ' -f3); do
      if egrep -q "^CREATE TABLE ${table} .+PRIMARY KEY *[,)]" "${normalised}"; then
         key="$(egrep "^CREATE TABLE ${table} " "${normalised}" | perl -lpe 's/^.+[(,] *([^, ]+) .+ PRIMARY KEY.+$/$1/')"

         echo "CREATE INDEX ${table}_primary_key ON ${table} (${key});" \
           >> "${target}"
      elif egrep -q "^CREATE TABLE ${table} .+PRIMARY KEY *[(]" "${normalised}"; then
         key="$(egrep "^CREATE TABLE ${table} " "${normalised}" | perl -lpe 's/^.+PRIMARY KEY *[(]([^)]+)[)].+$/$1/')"

         echo "CREATE INDEX ${table}_primary_key ON ${table} (${key});" \
           >> "${target}"
      else
         echo Table ${table} has no primary key. 1>&2
      fi
   done

   rm -f "${normalised}"

   cat >> "${target}" << TAIL

-------------------------------------------------------------------------------
TAIL

fi

#-----------------------------------------------------------------------------
