#! /bin/bash
#-----------------------------------------------------------------------------
#--  Set up:

echo "WARNING: Not really testing OpenID log-in using Google."; exit 0

cd "$(dirname "$0")" || exit 101

export LANG=C

name="$(basename "$0")"

#-----------------------------------------------------------------------------
#--  Log in (Alice):

wget --keep-session-cookies \
     --save-cookies    "${name}.cookies" \
     --output-document "${name}.fetch-1.html" \
     --output-file     "${name}.fetch-1.log" \
     'http://localhost:4242/users/log_in?openid=https://www.google.com/accounts/o8/id'

grep -A1000 '<form' "${name}.fetch-1.html" \
  | grep -B1000 '</form>' \
  | tr '\n' ' ' \
  | perl -lpe 's/>/>\n/g; s/  +/ /g;' \
  | egrep '<form|<input' \
  > "${name}.fetch-1.form"

if [ ! -s "${name}.fetch-1.form" ]; then
   rm -f "${name}.fetch-1.html"
else
   echo "No form data." 1>&2
   exit 102
fi

#-----------------------------------------------------------------------------
#--  Log in (Google):

url=$(egrep '<form .*action="' "${name}.fetch-1.form" | perl -lpe 's/^.+action="//; s/".+$//;')

hidden=$(egrep '<input .*type="(hidden|checkbox)"' "${name}.fetch-1.form" | perl -lpe 's/^.+name="([^"]+)" .*value=["'"'"']([^"'"'"']*)["'"'"'].+$/$1=$2/;'| tr '\n' '&')

secrets='Email=adaheads1@gmail.com&Passwd=wopeP9Li-Et6vah1k'

wget --post-data "${hidden}${secrets}" \
     --keep-session-cookies \
     --load-cookies    "${name}.cookies" \
     --save-cookies    "${name}.cookies" \
     --output-document "${name}.fetch-2.html" \
     --output-file     "${name}.fetch-2.log" \
     "${url}"

#-----------------------------------------------------------------------------
