#! /bin/bash
#-----------------------------------------------------------------------------
#--  Set up:

cd "$(dirname "$0")" || exit -1

errors=0

#-----------------------------------------------------------------------------
#--  Helper functions:

function check() {
   local failed=no
   local uri="$1"

   local name="${uri#/}"
   local name="${name//\//-}"

   local url="http://localhost:4242${uri}"

   local status_file="${name}.status"
   local data_file="${name}.expected"

   local data="${name}.data"
   local log="${name}.log"
   local differences="${name}.differences"

   if [ ! -f "${status_file}" ]; then
      echo "Please put the expected HTTP status code for <${url}> in '${status_file}'."
      let errors++
      return
   fi

   local expected_status="$(cat "${status_file}" | tr -cd '0-9')"

   if [ -z "${expected_status}" ]; then
      echo "'${status_file}' should contain the expected 3 digit HTTP status code for <${url}>."
      let errors++
      return
   fi

   if [ ! -f "${data_file}" ]; then
      echo "Please put the expected data from <${url}> in '${data_file}'."
      let errors++
      return
   fi
   
   curl -v "${url}" 1>"${data}" 2>"${log}"

   diff -u "${data_file}" "${data}" > "${differences}"

   if [ -s "${differences}" ]; then
      echo "Mismatch in output from the websocket interface <${url}>:"
      cat "${differences}"
      echo

      let errors++
      local failed=yes
   fi

   if grep "^< HTTP/1.1 "${expected_status}' ' "${log}" 1>/dev/null; then
      true
   else
      echo "Incorrect HTTP status from the websocket interface <${url}>:"
      egrep '^< HTTP/1.1 [0-9]{3] ' "${log}"

      let errors++
      local failed=yes
   fi

   if [ "${failed}" = "no" ]; then
      rm -f "${data}" "${log}" "${differences}"
   fi
}

#-----------------------------------------------------------------------------
#--  Make sure Alice is running:

../../../exe/alice \
  --alice-config-file ../../../exe/configuration/alice_config.ini \
  --yolk-config-file  ../sighup-handling/yolk_config.ini \
  1>alice.log 2>alice.errors &

alice_pid=$!

if [ -z "${alice_pid}" ]; then
   echo "Failed to start Alice." 1>&2
   exit -1
elif [ ! -d "/proc/${alice_pid}" ]; then
   echo "No process information directory for the started Alice." 1>&2
   exit -2
fi

#-----------------------------------------------------------------------------
#--  Wait for Alice to become ready:

sleep 1

#-----------------------------------------------------------------------------
#--  Actual checks:

check "/users/list"
check "/users/list?a"

check "/users/openids?user=Tux"
check "/users/openids"
check "/users/openids?user=Tux&a"
check "/users/openids?user=Jacob"
check "/users/openids?name=Jacob"

#-----------------------------------------------------------------------------
#--  Stop Alice:

kill ${alice_pid}
sleep 1
if [ -d /proc/${alice_pid} ]; then
   echo 'Killing Alice the hard way...' 1>&2
   kill -9 ${alice_pid}
fi

#-----------------------------------------------------------------------------
#--  Report errors:

if [ ${errors} -gt 0 ]; then
   echo "Failed at ${errors} tests."
fi

#-----------------------------------------------------------------------------
#--  Exit status:

exit ${errors}

#-----------------------------------------------------------------------------
