#! /bin/bash
#-----------------------------------------------------------------------------
#--  Set up:

cd "$(dirname "$0")" || exit -1

errors=0

#-----------------------------------------------------------------------------
#--  Output from show_user_list:

./show_user_list \
  --alice-config-file ../../../exe/configuration/alice_config.ini \
  --yolk-config-file  ../sighup-handling/yolk_config.ini \
  | diff -u show_user_list.expected_output - \
  > show_user_list.output_differences

if [ -s show_user_list.output_differences ]; then
   echo "Mismatch in output from 'show_user_list':"
   cat show_user_list.output_differences
   echo

   errors++
fi

rm -f show_user_list.output_differences

#-----------------------------------------------------------------------------
#--  Report errors:

if [ ${errors} -gt 0 ]; then
   echo "Failed at ${errors} tests."
fi

#-----------------------------------------------------------------------------
#--  Exit status:

exit ${errors}

#-----------------------------------------------------------------------------
