#! /bin/bash
#-----------------------------------------------------------------------------
#--  Set up:

cd "$(dirname "$0")" || exit -1

errors=0

#-----------------------------------------------------------------------------
#--  Make sure Alice is running:

../../../exe/alice \
  --alice-config-file ../../../exe/configuration/alice_config.ini \
  --yolk-config-file  ..//sighup-handling/yolk_config.ini \
  1>alice.log 2>alice.errors &

alice_pid=$!

if [ -z "${alice_pid}" ]; then
   echo "Failed to start Alice." 1>&2
   exit -1
elif [ ! -d "/proc/${alice_pid}" ]; then
   echo "No process information directory for the started Alice." 1>&2
   exit -2
fi

#-----------------------------------------------------------------------------
#--  Wait for Alice to become ready:

sleep 1

#-----------------------------------------------------------------------------
#--  Response from /users/list:

wget --quiet --output-document=user_list.json http://localhost:4242/users/list

diff -u user_list.expected.json user_list.json \
  > user_list.json.differences

if [ -s user_list.json.differences ]; then
   echo "Mismatch in output from the websocket interface '/users/list':"
   cat user_list.json.differences
   echo

   let errors++
fi

rm -f user_list.json user_list.json.differences

#-----------------------------------------------------------------------------
#--  Response from /users/openids:

wget --quiet --output-document=openids.json http://localhost:4242/users/openids?user=Tux

diff -u openids.expected.json openids.json \
  > openids.json.differences

if [ -s openids.json.differences ]; then
   echo "Mismatch in output from the websocket interface '/users/openids':"
   cat openids.json.differences
   echo

   let errors++
fi

rm -f openids.json openids.json.differences

#-----------------------------------------------------------------------------
#--  Stop Alice:

kill ${alice_pid}

(
  sleep 1
  if [ -d /proc/${alice_pid} ]; then
     echo 'Killing Alice the hard way...' 1>&2
     kill -9 ${alice_pid}
  fi
) &

#-----------------------------------------------------------------------------
#--  Report errors:

if [ ${errors} -gt 0 ]; then
   echo "Failed at ${errors} tests."
fi

#-----------------------------------------------------------------------------
#--  Exit status:

exit ${errors}

#-----------------------------------------------------------------------------
