#! /bin/bash
#-----------------------------------------------------------------------------
#--  Set up:

cd "$(dirname "$0")" || exit -1

errors=0

#-----------------------------------------------------------------------------
#--  Make sure Alice is running:

../../../exe/alice \
  --alice-config-file ../../../exe/configuration/alice_config.ini \
  --yolk-config-file  ..//sighup-handling/yolk_config.ini \
  1>alice.log 2>alice.errors &

alice_pid=$!

if [ -z "${alice_pid}" ]; then
   echo "Failed to start Alice." 1>&2
   exit -1
elif [ ! -d "/proc/${alice_pid}" ]; then
   echo "No process information directory for the started Alice." 1>&2
   exit -2
fi

#-----------------------------------------------------------------------------
#--  Wait for Alice to become ready:

sleep 1

#-----------------------------------------------------------------------------
#--  Response from /users/list:

curl -v http://localhost:4242/users/list \
  1> user_list.json \
  2> user_list.errors

diff -u user_list.expected.json user_list.json \
  > user_list.json.differences

if [ -s user_list.json.differences ]; then
   echo "Mismatch in output from the websocket interface '/users/list':"
   cat user_list.json.differences
   echo

   let errors++
fi

if grep '^< HTTP/1.1 200 ' user_list.errors 1>/dev/null; then
   true
else
   echo "Incorrect HTTP status from the websocket interface '/users/list':"
   egrep '^< HTTP/1.1 [0-9]{3] '
fi

rm -f user_list.json \
      user_list.errors \
      user_list.json.differences

#-----------------------------------------------------------------------------
#--  Response from '/users/list' with parameters:

curl -v http://localhost:4242/users/list?a \
  1> user_list-with_parameters.json \
  2> user_list-with_parameters.errors

diff -u user_list-with_parameters.expected.json \
        user_list-with_parameters.json \
      > user_list-with_parameters.json.differences

if [ -s user_list-with_parameters.json.differences ]; then
   echo "Mismatch in output from the websocket interface '/users/list' with parameters:"
   cat user_list-with_parameters.json.differences
   echo

   let errors++
fi

if grep '^< HTTP/1.1 400 ' user_list-with_parameters.errors 1>/dev/null; then
   true
else
   echo "Incorrect HTTP status from the websocket interface '/users/list':"
   egrep '^< HTTP/1.1 [0-9]{3] '
fi

rm -f user_list-with_parameters.json \
      user_list-with_parameters.errors \
      user_list-with_parameters.json.differences

#-----------------------------------------------------------------------------
#--  Response from /users/openids:

curl -v http://localhost:4242/users/openids?user=Tux \
  1> openids.json \
  2> openids.errors

diff -u openids.expected.json openids.json \
  > openids.json.differences

if [ -s openids.json.differences ]; then
   echo "Mismatch in output from the websocket interface '/users/openids':"
   cat openids.json.differences
   echo

   let errors++
fi

if grep '^< HTTP/1.1 200 ' openids.errors 1>/dev/null; then
   true
else
   echo "Incorrect HTTP status from the websocket interface '/users/list':"
   egrep '^< HTTP/1.1 [0-9]{3] '
fi

rm -f openids.json \
      openids.errors \
      openids.json.differences

#-----------------------------------------------------------------------------
#--  Stop Alice:

kill ${alice_pid}
sleep 1
if [ -d /proc/${alice_pid} ]; then
   echo 'Killing Alice the hard way...' 1>&2
   kill -9 ${alice_pid}
fi

#-----------------------------------------------------------------------------
#--  Report errors:

if [ ${errors} -gt 0 ]; then
   echo "Failed at ${errors} tests."
fi

#-----------------------------------------------------------------------------
#--  Exit status:

exit ${errors}

#-----------------------------------------------------------------------------
