with GNATCOLL.SQL; use GNATCOLL.SQL;
package Database_Names is
   pragma Style_Checks (Off);
   TC_Attribute : aliased constant String := """Attribute""";
   Ta_Attribute : constant Cst_String_Access := TC_Attribute'Access;
   TC_Contactentity : aliased constant String := """ContactEntity""";
   Ta_Contactentity : constant Cst_String_Access := TC_Contactentity'Access;
   TC_Contactentity_Attribute : aliased constant String := """ContactEntity_Attribute""";
   Ta_Contactentity_Attribute : constant Cst_String_Access := TC_Contactentity_Attribute'Access;
   TC_Contactentity_Organization : aliased constant String := """ContactEntity_Organization""";
   Ta_Contactentity_Organization : constant Cst_String_Access := TC_Contactentity_Organization'Access;
   TC_Contactentity_Tag : aliased constant String := """ContactEntity_Tag""";
   Ta_Contactentity_Tag : constant Cst_String_Access := TC_Contactentity_Tag'Access;
   TC_Organization : aliased constant String := """Organization""";
   Ta_Organization : constant Cst_String_Access := TC_Organization'Access;
   TC_Tag : aliased constant String := """Tag""";
   Ta_Tag : constant Cst_String_Access := TC_Tag'Access;

   NC_Attr_Description : aliased constant String := "attr_description";
   N_Attr_Description : constant Cst_String_Access := NC_attr_description'Access;
   NC_Attr_Id : aliased constant String := "attr_id";
   N_Attr_Id : constant Cst_String_Access := NC_attr_id'Access;
   NC_Attr_Name : aliased constant String := "attr_name";
   N_Attr_Name : constant Cst_String_Access := NC_attr_name'Access;
   NC_Attr_Value : aliased constant String := "attr_value";
   N_Attr_Value : constant Cst_String_Access := NC_attr_value'Access;
   NC_Ce_Id : aliased constant String := "ce_id";
   N_Ce_Id : constant Cst_String_Access := NC_ce_id'Access;
   NC_Ce_Name : aliased constant String := "ce_name";
   N_Ce_Name : constant Cst_String_Access := NC_ce_name'Access;
   NC_Employed_From : aliased constant String := "employed_from";
   N_Employed_From : constant Cst_String_Access := NC_employed_from'Access;
   NC_Employed_To : aliased constant String := "employed_to";
   N_Employed_To : constant Cst_String_Access := NC_employed_to'Access;
   NC_Isperson : aliased constant String := "isperson";
   N_Isperson : constant Cst_String_Access := NC_isperson'Access;
   NC_Org_Id : aliased constant String := "org_id";
   N_Org_Id : constant Cst_String_Access := NC_org_id'Access;
   NC_Org_Name : aliased constant String := "org_name";
   N_Org_Name : constant Cst_String_Access := NC_org_name'Access;
   NC_Sip_Uri : aliased constant String := """sip_URI""";
   N_Sip_Uri : constant Cst_String_Access := NC_sip_URI'Access;
   NC_Tag_Description : aliased constant String := "tag_description";
   N_Tag_Description : constant Cst_String_Access := NC_tag_description'Access;
   NC_Tag_Id : aliased constant String := "tag_id";
   N_Tag_Id : constant Cst_String_Access := NC_tag_id'Access;
   NC_Tag_Name : aliased constant String := "tag_name";
   N_Tag_Name : constant Cst_String_Access := NC_tag_name'Access;
end Database_Names;
