with GNATCOLL.SQL; use GNATCOLL.SQL;
package Database_Names is
   pragma Style_Checks (Off);
   TC_Dial_Plans : aliased constant String := """Dial_Plans""";
   Ta_Dial_Plans : constant Cst_String_Access := TC_Dial_Plans'Access;
   TC_Contact : aliased constant String := "contact";
   Ta_Contact : constant Cst_String_Access := TC_Contact'Access;
   TC_Contact_Attributes : aliased constant String := "contact_attributes";
   Ta_Contact_Attributes : constant Cst_String_Access := TC_Contact_Attributes'Access;
   TC_Contact_Recipients : aliased constant String := "contact_recipients";
   Ta_Contact_Recipients : constant Cst_String_Access := TC_Contact_Recipients'Access;
   TC_Kinds : aliased constant String := "kinds";
   Ta_Kinds : constant Cst_String_Access := TC_Kinds'Access;
   TC_Organization : aliased constant String := "organization";
   Ta_Organization : constant Cst_String_Access := TC_Organization'Access;
   TC_Organization_Contacts : aliased constant String := "organization_contacts";
   Ta_Organization_Contacts : constant Cst_String_Access := TC_Organization_Contacts'Access;
   TC_Recipient : aliased constant String := "recipient";
   Ta_Recipient : constant Cst_String_Access := TC_Recipient'Access;
   TC_Recipient_Kind : aliased constant String := "recipient_kind";
   Ta_Recipient_Kind : constant Cst_String_Access := TC_Recipient_Kind'Access;
   TC_Special_Days : aliased constant String := "special_days";
   Ta_Special_Days : constant Cst_String_Access := TC_Special_Days'Access;

   NC_Contact_Id : aliased constant String := "contact_id";
   N_Contact_Id : constant Cst_String_Access := NC_contact_id'Access;
   NC_Day : aliased constant String := """day""";
   N_Day : constant Cst_String_Access := NC_day'Access;
   NC_Description : aliased constant String := "description";
   N_Description : constant Cst_String_Access := NC_description'Access;
   NC_Dial_Plan : aliased constant String := "dial_plan";
   N_Dial_Plan : constant Cst_String_Access := NC_dial_plan'Access;
   NC_Email_Address : aliased constant String := "email_address";
   N_Email_Address : constant Cst_String_Access := NC_email_address'Access;
   NC_Full_Name : aliased constant String := "full_name";
   N_Full_Name : constant Cst_String_Access := NC_full_name'Access;
   NC_Id : aliased constant String := "id";
   N_Id : constant Cst_String_Access := NC_id'Access;
   NC_Is_Human : aliased constant String := "is_human";
   N_Is_Human : constant Cst_String_Access := NC_is_human'Access;
   NC_Json : aliased constant String := "json";
   N_Json : constant Cst_String_Access := NC_json'Access;
   NC_Kind : aliased constant String := "kind";
   N_Kind : constant Cst_String_Access := NC_kind'Access;
   NC_Kind_Id : aliased constant String := "kind_id";
   N_Kind_Id : constant Cst_String_Access := NC_kind_id'Access;
   NC_Organization_Id : aliased constant String := "organization_id";
   N_Organization_Id : constant Cst_String_Access := NC_organization_id'Access;
   NC_Phone_Number : aliased constant String := "phone_number";
   N_Phone_Number : constant Cst_String_Access := NC_phone_number'Access;
   NC_Recipient_Id : aliased constant String := "recipient_id";
   N_Recipient_Id : constant Cst_String_Access := NC_recipient_id'Access;
   NC_Uri : aliased constant String := "uri";
   N_Uri : constant Cst_String_Access := NC_uri'Access;
end Database_Names;
